name: ⚠️️ Bug report
description: Report a bug
title: "[BUG]: "
labels: ["Type: Bug"]
body:
  - type: input
    attributes:
      label: Current version
      description: Latest release to-date [found here](https://github.com/bayfrontmedia/openapi-parser/releases)
      placeholder: vX.X.X
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Detailed description of the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: Details of the environment which experienced this issue. e.g., IP address/location, OS, software version, etc.
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Can provide links to a live example, code snippets, screenshots, or other steps to reproduce this issue
  - type: textarea
    attributes:
      label: Possible solution
      description: Possible solution/fix for this issue