name: 📄 Other
description: All other issues
title: "[OTHER]: "
labels: ["Type: Other"]
body:
  - type: markdown
    attributes:
      value: |
        To create a new issue, complete the form below.
        Be sure to add "other" labels most relevant to this issue.
  - type: input
    attributes:
      label: Current version
      description: Latest release to-date [found here](https://github.com/bayfrontmedia/openapi-parser/releases)
      placeholder: vX.X.X
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Issue details
    validations:
      required: true